# SPDX-FileCopyrightText: 2020 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

# Selecting SL7 as the base OS
FROM fermilab/fnal-wn-sl7:latest
MAINTAINER WMS Team "glideinwms-support@fnal.gov"

# Default entry point
CMD ["/bin/bash"]

