# SPDX-FileCopyrightText: 2020 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

FROM localhost/factory-workspace
MAINTAINER Bruno Coimbra "coimbra@fnal.gov"
LABEL name="Devcontainer for the GlideinWMS Factory"

WORKDIR /tmp
